### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by chovanecadam** [coreruleset/modsecurity-crs-docker#103]
Link to the [Core Rule Set Slack Channel](https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ) referenced in the [Quick reference](https://github.com/coreruleset/modsecurity-crs-docker#quick-reference) section of the README.md file is broken.

**Comment by theseion** [comment]
Thanks! Opened PR to fix it.
