### ISSUE TITLE
Re-Build with httpd 2.4.55

### ISSUE THREAD

**Issue by rcanavan** [coreruleset/modsecurity-crs-docker#114]
Please re-build the official images so that they are based on httpd 2.4.55 - that update fixes 3 CVEs, all with severity medium.  

https://httpd.apache.org/security/vulnerabilities_24.html

**Comment by fzipi** [comment]
Yesterday there was a new release that should be using httpd 2.4.55. Can you verify and let us now @rcanavan?

**Comment by rcanavan** [comment]
Verifed. Thanks.

```
$ docker run --rm -ti --entrypoint /usr/local/apache2/bin/httpd owasp/modsecurity-crs:3.3.4-apache-alpine-202302060502  -v
Server version: Apache/2.4.55 (Unix)
Server built:   Jan 18 2023 05:07:53
```
