### ISSUE TITLE
Typo in Dockerhub repo description

### ISSUE THREAD

**Issue by irekkosek** [coreruleset/modsecurity-crs-docker#122]
Hi, i noticed a typo at the end of your Dockerhub repo description. (https://hub.docker.com/r/owasp/modsecurity-crs/)
In "Full docker run example of possible setup" there seems to be -p missing. It now looks like that:
`docker run -dti 80:80 --rm \`
and should look like that:
`docker run -dti -p 80:80 --rm \`

However this seems to not be the case on this github repo, where it's presented correctly.

**Comment by theseion** [comment]
Great catch, thanks!

**Comment by theseion** [comment]
@fzipi can you take this one?

**Comment by fzipi** [comment]
Yes. Looks like the README is not updating because we way high than the allowed limits for full description 🤔 

Limit is 25k chars.

```
❯ docker pushrm owasp/modsecurity-crs --debug
DEBU subcommand "pushrm" called
...
DEBU retrieve Dockerhub jwt token, status code: 200
DEBU push readme, response body: {"message":"httperror 400: request had 1 validation error","errinfo":{"fielderrors":{"full_description":"Exceeded max number of characters"}}}
DEBU push README, status code: 400
DEBU error pushing README, bad status code for response: 400 Bad Request
ERRO error pushing readme to repo server. See error message below. Run with "--debug" for more details.

error pushing README, bad status code for response: 400 Bad Request
❯ wc -c README.md
   34898 README.md
```

I think we might need to trim it down a bit?

**Comment by theseion** [comment]
Can we maybe create a custom readme for Dockerhub?

**Comment by fzipi** [comment]
Yes, that was my idea. But we need to see which parts we trim down.
