### ISSUE TITLE
ModSecurity was not compiled with JSON

### ISSUE THREAD

**Issue by Fillonj** [coreruleset/modsecurity-crs-docker#13]
Hello, I'm trying to build a waf based on Nginx + ModSecurity + CRS which log in logstash without blocking at first.

In my compose i've tried the images :
```
image: owasp/modsecurity-crs:nginx
image: owasp/modsecurity-crs:3.3-nginx
```
and in my modsecurity-override.conf i've tried :

```
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABCDEFGHIJKZ
SecAuditLogType  HTTPS
SecAuditLog http://xxx.xxx.xxx.xxx:port # URL logstash
```
or also

```
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABCDEFGHIJKZ
SecAuditLogType  Serial
SecAuditLogFormat JSON
SecAuditLog /var/log/modsec_audit.log
```

In every case i got the error "ModSecurity was not compiled with JSON" received by logstash or "{"error":"ModSecurity was not compiled with JSON support."}" in modsec_audit.log

This is certainly related to the opened bug detected on the owasp/modsecurity image on which are based the images I used : https://github.com/coreruleset/modsecurity-docker/issues/42

Regards

**Comment by Fillonj** [comment]
For information,
i've rebuild the owasp/modsecurity:nginx docker image and then i've rebuild the owasp/modsecurity-crs:3.3-nginx docker image this time basing it on my previously build modsecurity image without changing anything else in the Dockerfiles, and it works. 
The JSON parser is working when i use the HTTPS mode to send the logs to my ELK

**Comment by fzipi** [comment]
Agreed. I've verified this also and works as expected.
