### ISSUE TITLE
Add ErrorLogFormat as Apache variable

### ISSUE THREAD

**Issue by dikkatdeli** [coreruleset/modsecurity-crs-docker#136]
Hi,

I want to use Fail2ban to block client Ips with modsecurity-crs-docker but the error log does not contain X-Real-Ip. 

Error Log:

[security2:error] [pid 79:tid 140411823306496] [client 172.19.0.4:40730] [client 172.19.0.4] ModSecurity: Warning. Matched phrase 

How can I get X-Real-Ip from log to use fail2ban?

**Comment by airween** [comment]
Hi @dikkatdeli,

may be you should take a look to [ErrorLogFormat](https://httpd.apache.org/docs/2.4/mod/core.html#errorlogformat) directive in your Apache config (generally it's not set). I think you need something like this:

```
ErrorLogFormat "[%t] [%l] [pid %P] %F: %E: [client %{X-Real-Ip}i] %M
```

**Comment by dikkatdeli** [comment]
> Hi @dikkatdeli,
> 
> may be you should take a look to [ErrorLogFormat](https://httpd.apache.org/docs/2.4/mod/core.html#errorlogformat) directive in your Apache config (generally it's not set). I think you need something like this:
> 
> ```
> ErrorLogFormat "[%t] [%l] [pid %P] %F: %E: [client %{X-Real-Ip}i] %M
> ```

modsecurity-crs-docker doesn't have ErrorLogFormat  ENV variable.

Should I use APACHE_LOGFORMAT ?

**Comment by airween** [comment]
> modsecurity-crs-docker doesn't have ErrorLogFormat ENV variable.

You are right, this image does not contain `ErrorLogFormat` or any equivalent variable.

I thought you should try to add it by hand (I mean log in to the container and edit the configuration file), or try to mount the config (if it is possible) to test it, it works at least.

> Should I use APACHE_LOGFORMAT ?

Not for this. That's a completely different variable.

**Comment by fzipi** [comment]
Hi @dikkatdeli, the variable name you need to use for this is `APACHE_ERRORLOG_FORMAT`.
