### ISSUE TITLE
RESTRICTED_HEADERS default is not accurate

### ISSUE THREAD

**Issue by kilbiller** [coreruleset/modsecurity-crs-docker#137]
Hi,

We started to run `owasp/modsecurity-crs:3.3.4-nginx-alpine-202303180303` in `DetectionOnly` mode before turning it on in prod and we get a lot of logs on rule id `920450`.

In the log we see that `/accept-charset/` is part of the rule (`/accept-charset/ /content-encoding/ /proxy/ /lock-token/ /content-range/ /if/`) but we have not changed the default and the README says the following: `Restricted_headers (Default: /proxy/ /lock-token/ /content-range/ /if/)`

We get a lot of logs for this rule so we are going to change the value for our case. I don't know if it's a bug or the doc is lagging behind but I tought you should know.

**Comment by airween** [comment]
Hi @kilbiller,

`Accept-Charset` header is [deprecated](https://bugs.chromium.org/p/chromium/issues/detail?id=112804) since 2012.

I think the best thing what you can do in this case that make an exclusion for for rule 920450, eg.

```
SecRule REQUEST_URI "@beginsWith /your/uri/which/triggers/the/rule" \
    "id:100001,\
    phase:1,\
    t:none,\
    nolog,\
    ctl:ruleRemoveById=920450"
```

You should put this exclusion **BEFORE** CRS, eg. `REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`.

**Comment by fzipi** [comment]
@kilbiller Do you have any specific user agent that is sending this?

**Comment by kilbiller** [comment]
Oh I didn't know it was deprecated, the doc should probably be updated then.

@airween It happens on random urls

@fzipi Nothing specific, here's some of them
- `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36`
- `ZoominfoBot (zoominfobot at zoominfo dot com)`
- `Mozilla/5.0/Firefox/42.0 - nbertaupete95(at)gmail.com`
- `Mozilla/5.0`

**Comment by fzipi** [comment]
> @fzipi Nothing specific, here's some of them
> 
>     * `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36`
> 
>     * `ZoominfoBot (zoominfobot at zoominfo dot com)`
> 
>     * `Mozilla/5.0/Firefox/42.0 - nbertaupete95(at)gmail.com`
> 
>     * `Mozilla/5.0`

Firefox 42? That's old. Like really old. 😄
