### ISSUE TITLE
Update sources?

### ISSUE THREAD

**Issue by shiz0** [coreruleset/modsecurity-crs-docker#14]
Docker Hub for these images (https://hub.docker.com/r/owasp/modsecurity-crs/), as well as the Dockerfiles in here, both link the now archived repo https://github.com/SpiderLabs/owasp-modsecurity-crs
Shouldn't they be updated to link/pull from here now?
I'm thinking about using them to host some sites, but I'm unsure about if they will get future updates like this.
Thanks.

**Comment by bittner** [comment]
The README on Docker Hub is not updated automatically since we build the images with GitHub Actions and don't let Docker Hub take care of it. That needs to be updated manually. Thanks for reporting!

**Comment by shiz0** [comment]
Thank you for pointing out that the docker Hub images are actually built from this repo.
What about the Dockerfiles in here? They also seem to reference the archived one:
https://github.com/coreruleset/modsecurity-crs-docker/blob/master/3.3-nginx/Dockerfile
https://github.com/coreruleset/modsecurity-crs-docker/blob/master/3.3-apache/Dockerfile

**Comment by bittner** [comment]
The repository was moved only recently. You can expect most if not all absolute URLs to point to the "wrong" location. If you want to try a PR to fix the situation that would be helpful. Only the `master` branch is relevant, you can ignore all other branches.

**Comment by shiz0** [comment]
I hope the PR is fine like that.
Which `master` branch do you mean? This repo here only has that one.
Maybe those in https://github.com/coreruleset/modsecurity-docker? If I understood correctly, those are obsoleted to reduce images to just two variants, developed under `master`? I checked there as well, but did not find any references to the archived repo.

**Comment by bittner** [comment]
That's correct, there is only a single branch here. I mixed this up with the [modsecurity-docker](https://github.com/coreruleset/modsecurity-docker/) repository. Sorry!
