### ISSUE TITLE
[Help] Reference configuration to use modsecurity with nginx

### ISSUE THREAD

**Issue by lordraiden** [coreruleset/modsecurity-crs-docker#145]
Currently a have nginx (swag) running in docker.
What would be the best way to add modsecurity to it?

Does modsecurity-crs-docker container has everything required? or it's just an extension of modsecurity?

I'm trying to understand how to do it and the architecture something like.

internet --> modsecurity-crs-docker --> nginx --> app1, app2, app3

Can modsecurity-crs-docker work in parallel and still block? like

```
            modsecurity-crs-docker 
               |
internet --> nginx ------> app1, app2, app3
```

And who the configuration should be in modsecurity-crs-docker to be linked with nginx

Any example, particularly in docker compose would be welcome.

**Comment by franbuehler** [comment]
The modsecurity-crs-docker container is based on an NGINX image. It compiles and installs ModSecurity and adds the OWASP Core Rule Set. See here: https://github.com/coreruleset/modsecurity-crs-docker/blob/master/nginx/Dockerfile

I think the easiest way is to add the modsecurity-crs-docker container in front of your container. And then to set your container as BACKEND variable. 
An example docker-compose.yml can be found here:
https://github.com/coreruleset/coreruleset/blob/v4.0/dev/tests/docker-compose.yml.

The modsecurity-crs-docker container can't be run in parallel.
