### ISSUE TITLE
End of life nginx version

### ISSUE THREAD

**Issue by Boschman** [coreruleset/modsecurity-crs-docker#146]
The current version of nginx being used (1.22.1) has reached its end of life. See: https://endoflife.date/nginx

**Comment by Boschman** [comment]
I've created a pull request that updates nginx to version 1.25.0: https://github.com/coreruleset/modsecurity-crs-docker/pull/148

**Comment by theseion** [comment]
Thanks!

**Comment by fzipi** [comment]
Fixed in #148
