### ISSUE TITLE
nginx won't reverseproxy (missing proxy variables in default.conf)

### ISSUE THREAD

**Issue by shiz0** [coreruleset/modsecurity-crs-docker#15]
The default.conf used for the nginx image:
https://github.com/coreruleset/modsecurity-crs-docker/blob/master/3.3-nginx/conf.d/default.conf
does not include proxy info, like the one of the parent image does:
https://github.com/coreruleset/modsecurity-docker/blob/master/v3-nginx/conf.d/default.conf

I was able to get it to proxy by mounting a default.conf to the image which included some of the parent image conf's values.
Had to remove some variables which could not be resolved and change the proxy pass line to 
proxy_pass http://${UPSTREAM}/;
It redirected me, but still threw some "header ..." alerts. probably missed some other setting.

**Comment by bittner** [comment]
That's true. All the configuration needed is already included in the base image. The [default.conf](https://github.com/coreruleset/modsecurity-crs-docker/blob/master/3.3-nginx/conf.d/default.conf) in this repository should hence be deleted.

Do you want to verify whether deleting the file and removing [its related line in the Dockerfile](https://github.com/coreruleset/modsecurity-crs-docker/blob/master/3.3-nginx/Dockerfile#L29) works out? Would be awesome if you could then prepare that as a PR to fix the issue.

**Comment by jsommerville-untangle** [comment]
See the PR I opened addressing the above, but something that looks to still be an issue in the base image, is DNS_SERVER required for non-reverse proxy situations in the base image as well? Seems like you will see this error if it's not passed in:

 `2021/01/22 23:43:39 [emerg] 1#1: no name servers defined in /etc/nginx/conf.d/default.conf:13
nginx: [emerg] no name servers defined in /etc/nginx/conf.d/default.conf:13`

**Comment by jsommerville-untangle** [comment]
I see the issue to my above comment, this exists in the base image but not in this nginx image:
https://github.com/coreruleset/modsecurity-docker/blob/3fbeb6663f140082ada02ee3229fc07a25276368/v3-nginx/docker-entrypoint.sh#L3

I force pushed the PR branch, adding in the entrypoint DNS_SERVER export and removing the commit adding the DNS_SERVER env variable into the 3.3-nginx/Dockerfile

**Comment by fzipi** [comment]
@jsommerville-untangle Thanks for the PR, merged the fix.
