### ISSUE TITLE
Logging in Nginx in DetectionOnly mode

### ISSUE THREAD

**Issue by WizbangRob** [coreruleset/modsecurity-crs-docker#159]
I have a basic setup with the following environment variables set: 

      - name: MODSEC_RULE_ENGINE
        value: 'DetectionOnly'
      - name: SERVER_NAME
        value: example.com.au
      - name: PROXY_SSL
        value: 'on'
      - name: PROXY
        value: '1'
      - name: BACKEND
        value: https://examplebackend.com.au

If I switch MODSEC_RULE_ENGINE to on, then rule breaches get blocked and logged. If I switch to DetectionOnly, as expected, they don't get blocked, but they also don't get logged in /var/log/nginx/error.log or /var/log/nginx/access.log.

Where can I find the logging so that I can work through the false positives?

Also, how can I switch between on and DetectionOnly without restarting the Docker container? I've tried adding SecRuleEngine On in modsecurity.conf.template and running nginx -s reload, but it doesn't seem to change modes

**Comment by theseion** [comment]
Sorry for the delay.

>If I switch MODSEC_RULE_ENGINE to on, then rule breaches get blocked and logged. If I switch to DetectionOnly, as expected, they don't get blocked, but they also don't get logged in /var/log/nginx/error.log or /var/log/nginx/access.log.

That sounds like a bug. I'll try to recreate the issue.

>Also, how can I switch between on and DetectionOnly without restarting the Docker container? I've tried adding SecRuleEngine On in modsecurity.conf.template and running nginx -s reload, but it doesn't seem to change modes

You should be able to  modify the values by modifying the files inside the running container, e.g.,

```shell
docker exec -it modsec3-nginx bash
apt update
apt install -y vim
vim /etc/modsecurity.d/modsecurity.conf
```

**Comment by theseion** [comment]
I've tried to recreate your issue with `MODSEC_RULE_ENGINE` but haven't been able to. We use `DetectionOnly` to run our CRS test suite so I'm sure that it works. `PROXY` is actually not used in our images anymore, that's a left-over in the documentation. I'll open an issue to fix that.

I would have to see more of your setup to figure out what's going on.

**Comment by fzipi** [comment]
Hi @WizbangRob! Any additional comments here, or do we close it?

**Comment by fzipi** [comment]
Closing.
