### ISSUE TITLE
Any ideas how to geoblock or geowhitelist

### ISSUE THREAD

**Issue by sbe-arg** [coreruleset/modsecurity-crs-docker#160]
Any suggestions how to geoblock or geowhitelist country lists?

Thanks heaps

**Comment by theseion** [comment]
Hi @sbe-arg. First, you'll need to set up ModSecurity for geo blocking. See https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#geolookup. Once you have that, you will have to mount the required files (database and rules) into the container and that should be it, more or less.

We do not usually recommend geo blocking as the mapping of IPs to regions is fuzzy. Also note that there are two formats of the GeoIP database and that ModSecurity does not support the new version. That being said, you might be able to use the following script to convert the database: https://github.com/emphazer/GeoIP_convert-v2-v1.

If you have concrete questions about setting up geo blocking that are not covered by the ModSecurity documentation, please open an issue in the https://github.com/coreruleset/coreruleset repository. If you have concrete questions about configuring one of our containers for geo blocking, feel free to open a new issue in this repository.

I'll close this issue as your question is really a bit too broad too be answered here.

**Comment by theseion** [comment]
I forgot to add that there's a plugin for CRS v4.0 (upcoming) that adds geo IP support to CRS (you'll still need to set up things yourself): https://github.com/azurit/modsecurity-geoip-plugin
