### ISSUE TITLE
Seeking Help: Unable to Access Docker Container via Configured Port After Launch

### ISSUE THREAD

**Issue by iLern** [coreruleset/modsecurity-crs-docker#161]
I pulled the image owasp/modsecurity-crs:3.3.5-nginx-202308071108 from Docker Hub and mapped the container's port 80 to port 8090 on the host. 

However, when I try to access localhost:8090, I receive a `400 Bad Request Request Header Or Cookie Too Large` error. 
<img width="377" alt="image" src="https://github.com/coreruleset/modsecurity-crs-docker/assets/43905872/49ef5c40-2a1d-41ec-b5d5-0fcb9dacf2a0">

Upon checking the logs, I found that the request is being repeatedly forwarded to IP address 172.17.0.1. 
<img width="1512" alt="image" src="https://github.com/coreruleset/modsecurity-crs-docker/assets/43905872/dcb006b5-3d0c-4671-8908-a84a1b2b1380">

I haven't made any additional configurations.  Just pull, run and try to access.

I've tried using private mode but it doesn't work.
My docker version is v24.0.5, OS is MacOS 13.4.1.

Has anyone else encountered a similar issue, and if so, how was it resolved? Thanks a lot.

**Comment by brkcdnxplt** [comment]
Try providing a backend using one of the environment variables. For example: 

 docker run --name test -p 80:80 --env BACKEND=http://your.ip.address -d --rm owasp/modsecurity-crs:3.3.5-nginx-202308071108

**Comment by fzipi** [comment]
@iLern Were you able to solve this problem?

**Comment by theseion** [comment]
Closing this issue as stale. @iLern, please reopen if you have more information to share.
