### ISSUE TITLE
can't block ip after setvar:ip.blocked=1

### ISSUE THREAD

**Issue by alex16999** [coreruleset/modsecurity-crs-docker#165]
I use this one https://github.com/coreruleset/modsecurity-crs-docker/blob/master/nginx/Dockerfile  build a new image , add the lmdb support(line50:./configure --with-lmdb --with-yajl --with-ssdeep --with-geoip --with-pcre2 --enable-silent-rules; \), MODSEC_VERSION=3.0.10 LMDB_VERSION=0.9.29  platform: linux nginx

my custom rules:

> Rule 1: Detect a 403 response and flag the IP address
> SecRule RESPONSE_STATUS "@streq 403" \
> "id:12345,phase:5,pass,nolog,\
> setvar:ip.blocked=1,expirevar:ip.blocked=3600"
> 
> Rule 2: Check for flagged IP addresses and block them
> SecRule ip.blocked "@eq 1" \
> "id:12346,phase:1,deny,status:403,nolog"
> 

Subsequently, I made two requests. The first request triggered a 403 response, while the second request was a normal one (expected to return 403). However, the second request did not trigger a 403 response.

Afterwards, I checked the data in modsec-shared-collections: 

> key: 0x7f5ed1f3dfbc myip_23caa51e7f6e1ea054a79ac5576c7f07712ac2f9::::blocked, data: 0x7f5ed1f3dfff 1.

Indeed, the IP has been recorded in the lmdb.

But why wasn't the second request detected and subsequently blocked?

Below is the debug log:

rule 12345:

> [169449429075.432313] [/.env] [9] This phase consists of 57 rule(s).
> [169449429075.432313] [/.env] [4] (Rule: 12345) Executing operator "StrEq" with param "403" against RESPONSE_STATUS.
> [169449429075.432313] [/.env] [9] Target value: "403" (Variable: RESPONSE_STATUS)
> [169449429075.432313] [/.env] [9] Matched vars updated.
> [169449429075.432313] [/.env] [4] Running [independent] (non-disruptive) action: setvar
> [169449429075.432313] [/.env] [8] Saving variable: IP:blocked with value: 1
> [169449429075.432313] [/.env] [4] Rule returned 1.
> [169449429075.432313] [/.env] [9] Running action: nolog
> [169449429075.432313] [/.env] [9] Running action: expirevar
> [169449429075.432313] [/.env] [4] Running (disruptive)     action: pass.
> [169449429075.432313] [/.env] [8] Running action pass
> 
> 16944942919.760660] [/] [9] This phase consists of 57 rule(s).
> [16944942919.760660] [/] [4] (Rule: 12345) Executing operator "StrEq" with param "403" against RESPONSE_STATUS.
> [16944942919.760660] [/] [9] Target value: "200" (Variable: RESPONSE_STATUS)
> [16944942919.760660] [/] [4] Rule returned 0.
> [16944942919.760660] [/] [9] Matched vars cleaned.

rule 123456:

> [16944942919.760660] [/] [9] Running action: nolog
> [16944942919.760660] [/] [4] Running (disruptive)     action: pass.
> [16944942919.760660] [/] [8] Running action pass
> [16944942919.760660] [/] [4] (Rule: 12346) Executing operator "Eq" with param "1" against IP:blocked.
> [16944942919.760660] [/] [4] Rule returned 0.
> [16944942919.760660] [/] [9] Matched vars cleaned.
> 
> 169449429075.432313] [/.env] [8] Running action pass
> [169449429075.432313] [/.env] [4] (Rule: 12346) Executing operator "Eq" with param "1" against IP:blocked.
> [169449429075.432313] [/.env] [4] Rule returned 0.
> [169449429075.432313] [/.env] [9] Matched vars cleaned.

**Comment by franbuehler** [comment]
Hi!

I tested your rules and this variant here should work. At least it works on my machine:

```
# initcol
SecAction phase:1,id:109,initcol:ip=%{REMOTE_ADDR},nolog

# Rule 1: Detect a 403 response and flag the IP address
SecRule RESPONSE_STATUS "@Streq 403" \ 
"id:12345,phase:5,pass,setvar:ip.blocked=1,expirevar:ip.blocked=3600,msg:'Status 403 returned, blocking ip.'"

# Rule 2: Check for flagged IP addresses and block them
SecRule ip:blocked "@eq 1" "id:12346,phase:1,deny,status:403,msg:'This ip has been blocked before.'"
```

Can you test with these rules?
I had to rename the variable name to ip:blocked in rule 12346 and also add an initcol SecAction.
I also removed the nolog so that we have more info in the error.log.

**Comment by alex16999** [comment]
@franbuehler  Thanks for your reply!!

I have already test the rules you give me.

# initcol
SecAction "phase:1,id:109,initcol:global=global,initcol:ip=%{REMOTE_ADDR},log"

# Rule 1: Detect a 403 response and flag the IP address
SecRule RESPONSE_STATUS "@Streq 403" "id:12345,phase:5,pass,nolog,setvar:ip.blocked=1,expirevar:ip.blocked=3600,msg:'Status 403 returned, blocking ip.'"

# Rule 2: Check for flagged IP addresses and block them
SecRule ip.blocked "@eq 1" "id:12346,phase:1,deny,status:403,nolog,msg:'This ip has been blocked before.'"

Still not work.  

modsec-shared-collections:
    # ./lmdbread tmp/modsec-shared-collections
    key: 0x7fa08cab4fbc myid_23caa51e7f6e1ea054a79ac5576c7f07712ac2f9::::blocked, data: 0x7fa08cab4fff 1

debug log:
rule 197:

> [169458424753.095332] [/.env] [4] Starting phase REQUEST_HEADERS.  (SecRules 1)
> [169458424753.095332] [/.env] [9] This phase consists of 197 rule(s).
> [169458424753.095332] [/.env] [4] (Rule: 109) Executing unconditional rule...
> [169458424753.095332] [/.env] [9] Running action: log
> [169458424753.095332] [/.env] [9] Saving transaction to logs
> [169458424753.095332] [/.env] [9] Running action: tag
> [169458424753.095332] [/.env] [9] Rule tag: modsecurity
> [169458424753.095332] [/.env] [9] Running action: initcol
> [169458424753.095332] [/.env] [5] Collection `global' initialized with value: global
> [169458424753.095332] [/.env] [9] Running action: initcol
> [169458424753.095332] [/.env] [5] Collection `ip' initialized with value: 180.210.206.208
> [169458424753.095332] [/.env] [9] Running action: log

rule 12345:

> [169458424753.095332] [/.env] [4] (Rule: 12345) Executing operator "StrEq" with param "403" against RESPONSE_STATUS.
> [169458424753.095332] [/.env] [9] Target value: "403" (Variable: RESPONSE_STATUS)
> [169458424753.095332] [/.env] [9] Matched vars updated.
> [169458424753.095332] [/.env] [4] Running [independent] (non-disruptive) action: setvar
> [169458424753.095332] [/.env] [8] Saving variable: IP:blocked with value: 1
> [169458424753.095332] [/.env] [4] Rule returned 1.
> [169458424753.095332] [/.env] [9] Saving msg: Status 403 returned, blocking ip.
> 
> [169458425143.957922] [/] [4] (Rule: 12345) Executing operator "StrEq" with param "403" against RESPONSE_STATUS.
> [169458425143.957922] [/] [9] Target value: "200" (Variable: RESPONSE_STATUS)
> [169458425143.957922] [/] [4] Rule returned 0.
> [169458425143.957922] [/] [9] Matched vars cleaned.

rule 12346:

> [169458424753.095332] [/.env] [4] (Rule: 12346) Executing operator "Eq" with param "1" against IP:blocked.
> [169458424753.095332] [/.env] [4] Rule returned 0.
> [169458424753.095332] [/.env] [9] Matched vars cleaned.
> 
> [169458425143.957922] [/] [4] (Rule: 12346) Executing operator "Eq" with param "1" against IP:blocked.
> [169458425143.957922] [/] [4] Rule returned 0.
> [169458425143.957922] [/] [9] Matched vars cleaned.


After test above I grep the rules with 'initcol' from owasp-crs/

I noticed the ip key in modsec-shared-collections with the  suffix "_%{tx.ua_hash}", so I changed the rule(901321) in REQUEST-901-INITIALIZATION.conf

from

initcol:ip=%{remote_addr}_%{tx.ua_hash},\

to 

initcol:ip=%{remote_addr},\

and removed rule 197,  ip key in modsec-shared-collections changed to myip without suffix "_%{tx.ua_hash}" but rule 12346 still not block.

here is the log:

modsec-shared-collections: 
# ./lmdbread tmp/modsec-shared-collections
key: 0x7f5cc57b3fe4 myip::::blocked, data: 0x7f5cc57b3ffe 1

debug log:
rule 901321:

> [169458509449.036270] [/.env] [4] (Rule: 901321) Executing unconditional rule...
> [169458509449.036270] [/.env] [4] Running [independent] (non-disruptive) action: setvar
> [169458509449.036270] [/.env] [8] Saving variable: TX:real_ip with value: 180.210.206.208
> [169458509449.036270] [/.env] [9] Running action: log
> [169458509449.036270] [/.env] [9] Saving transaction to logs
> [169458509449.036270] [/.env] [9] Running action: tag
> [169458509449.036270] [/.env] [9] Rule tag: modsecurity
> [169458509449.036270] [/.env] [9] Running action: nolog
> [169458509449.036270] [/.env] [9] Running action: initcol
> [169458509449.036270] [/.env] [5] Collection `global' initialized with value: global
> [169458509449.036270] [/.env] [9] Running action: initcol
> [169458509449.036270] [/.env] [5] Collection `ip' initialized with value: myip
> [169458509449.036270] [/.env] [4] Running (disruptive)     action: pass.
> [169458509449.036270] [/.env] [8] Running action pass
> 
> [169458509629.879483] [/] [4] (Rule: 901321) Executing unconditional rule...
> [169458509629.879483] [/] [4] Running [independent] (non-disruptive) action: setvar
> [169458509629.879483] [/] [8] Saving variable: TX:real_ip with value: myip
> [169458509629.879483] [/] [9] Running action: log
> [169458509629.879483] [/] [9] Saving transaction to logs
> [169458509629.879483] [/] [9] Running action: tag
> [169458509629.879483] [/] [9] Rule tag: modsecurity
> [169458509629.879483] [/] [9] Running action: nolog
> [169458509629.879483] [/] [9] Running action: initcol
> [169458509629.879483] [/] [5] Collection `global' initialized with value: global
> [169458509629.879483] [/] [9] Running action: initcol
> [169458509629.879483] [/] [5] Collection `ip' initialized with value: 180.210.206.208
> [169458509629.879483] [/] [4] Running (disruptive)     action: pass.
> [169458509629.879483] [/] [8] Running action pass

rule 12345:

> [169458509449.036270] [/.env] [4] (Rule: 12345) Executing operator "StrEq" with param "403" against RESPONSE_STATUS.
> [169458509449.036270] [/.env] [9] Target value: "403" (Variable: RESPONSE_STATUS)
> [169458509449.036270] [/.env] [9] Matched vars updated.
> [169458509449.036270] [/.env] [4] Running [independent] (non-disruptive) action: setvar
> [169458509449.036270] [/.env] [8] Saving variable: IP:blocked with value: 1
> [169458509449.036270] [/.env] [4] Rule returned 1.
> [169458509449.036270] [/.env] [9] Saving msg: Status 403 returned, blocking ip.
> [169458509449.036270] [/.env] [9] Running action: nolog
> [169458509449.036270] [/.env] [9] Running action: expirevar
> [169458509449.036270] [/.env] [4] Running (disruptive)     action: pass.
> [169458509449.036270] [/.env] [8] Running action pass
> 
> [169458509629.879483] [/] [4] (Rule: 12345) Executing operator "StrEq" with param "403" against RESPONSE_STATUS.
> [169458509629.879483] [/] [9] Target value: "200" (Variable: RESPONSE_STATUS)
> [169458509629.879483] [/] [4] Rule returned 0.
> [169458509629.879483] [/] [9] Matched vars cleaned.

rule 12346:

> [169458509449.036270] [/.env] [4] (Rule: 12346) Executing operator "Eq" with param "1" against IP:blocked.
> [169458509449.036270] [/.env] [4] Rule returned 0.
> [169458509449.036270] [/.env] [9] Matched vars cleaned.
> 
> [169458509629.879483] [/] [4] (Rule: 12346) Executing operator "Eq" with param "1" against IP:blocked.
> [169458509629.879483] [/] [4] Rule returned 0.
> [169458509629.879483] [/] [9] Matched vars cleaned.

And this is my setup.conf:

> Include /etc/modsecurity.d/customize/test.conf
> 
> Include /etc/modsecurity.d/modsecurity.conf
> 
> Include /etc/modsecurity.d/owasp-crs/crs-setup.conf
> 
> Include /etc/modsecurity.d/owasp-crs/rules/*.conf

I want to know why ModSecurity didn't load the value set in modsec-shared-collections. Is there any way to see the process of loading variables or to determine at which step a problem occurred? I currently don't know how to debug this.

Thanks again!

**Comment by RedXanadu** [comment]
I hope this isn't too off-track, but to offer some general advice: be very cautious if using or relying on ModSecurity's persistent collections functionality. It has a history of poor performance, unusual errors, race conditions, memory problems, and more. It is also very tricky to write correct rules and even trickier to troubleshoot.

There are almost always better places to maintain stateful information than within ModSecurity itself.

**Comment by alex16999** [comment]
@franbuehler 

> # initcol
> SecAction "phase:1,id:109,initcol:ip=%{REMOTE_ADDR},nolog"
> 
> # Rule 1: Detect a 403 response and flag the IP address
> SecRule RESPONSE_STATUS "@Streq 403" "id:12345,phase:5,pass,setvar:ip.blocked=1,expirevar:ip.blocked=3600,msg:'Status 403 returned, blocking ip.'"
> 
> # Rule 2: Check for flagged IP addresses and block them
> SecRule ip:blocked "@eq 1" "id:12346,phase:1,deny,status:403,msg:'This ip has been blocked before.'"
> 

Because my rule before Include /etc/modsecurity.d/owasp-crs/rules/*.conf  , so I changed the REQUEST-901-INITIALIZATION.conf 

from 

> initcol:ip=%{remote_addr}_%{tx.ua_hash},\  

to 

> initcol:ip=%{remote_addr},\

and it works,  thank you very much!

**Comment by franbuehler** [comment]
You're very welcome!

**Comment by RedXanadu** [comment]
> Besides maintaining variables internally in ModSecurity, any others suggestions I can look into?

@alex16999 Quite often, ModSecurity is sandwiched by or integrated with proxies, load balancers, web servers, etc. These are usually better equipped and well designed to handle stateful connection information at high speeds and at great scale.

For one example, I like using HAProxy, with its "stick tables", to handle the storing and updating of stateful information, and to communicate between HAProxy and ModSecurity using request and response headers. The same mechanism also allows for things like easy request rate limiting. There are many similar possible ideas :slightly_smiling_face:

**Comment by alex16999** [comment]
@RedXanadu 

> and to communicate between HAProxy and ModSecurity using request and response headers.

Combining other tools and leveraging their different features to meet my needs, thank you for your response, it's very helpful to me. I appreciate it!
