### ISSUE TITLE
Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by sunnoy** [coreruleset/modsecurity-crs-docker#186]
version: '3'

services:
  modsecurity:
    image: owasp/modsecurity-crs:3.3.5-nginx-202401080101
    ports:
      - "899:443"
    restart: always

**Comment by theseion** [comment]
The image is configured to act as reverse proxy by default (see https://github.com/coreruleset/modsecurity-crs-docker?tab=readme-ov-file#proxying). You need to either turn of proxy mode or provide a backend, as described in the documentation.
