### ISSUE TITLE
Add More Architectures

### ISSUE THREAD

**Issue by stellarpower** [coreruleset/modsecurity-crs-docker#19]
More or less what it says on the tin. Currently it seems only the AMD64 image is available on Docker Hub, I don't know if other builds are made or are in the pipeline but it would be good to support some other systems, e.g. ARM for SoC servers, or i386 for the odd bit of legacy hardware.

As an aside, I had some further comments about the Docker Hub page, should I open a new issue, or wait until #18 is closed?

**Comment by fzipi** [comment]
Hey! Regarding the docker hub page, probably #23 will fix it.

**Comment by fzipi** [comment]
Fixed the bad URI in the Docker Hub page.

Regarding adding more architectures, from what I see from official images for https://github.com/docker-library/httpd for example, some are unstable.

Also, we might not be able to support *all* additional architectures, so let's see which ones might be good for our case and why.

**Comment by fzipi** [comment]
We are now building 4 different architectures 🎉 .
