### ISSUE TITLE
Reduce release build time

### ISSUE THREAD

**Issue by theseion** [coreruleset/modsecurity-crs-docker#196]
Release builds currently take around 12 hours. We should reduce the build time. Some ideas:
- don't split jobs by container registry; both jobs will have to run the full build just to create the same images
- split by web server variant; that should give us the most reusability

**Comment by fzipi** [comment]
There is one more thing that we can do, that will give us real optimization: split the builds by arch. It was not possible before because of the manifest, but now it can be done with an extra step that recreates the manifest at the end...

**Comment by theseion** [comment]
I had already updated the PR to create jobs for each combination of (target, platform), but I realised that platforms are target specific (we only build OpenResty for two platforms). So instead of just reading `platforms-base` we would have to build up a map of actual (target, platform) combinations for the matrix. That was too complicated for just a quick change, so I reverted it.

**Comment by theseion** [comment]
Which manifest are you talking about, btw?
