### ISSUE TITLE
Add Modsecurity version to startup logging

### ISSUE THREAD

**Issue by ne20002** [coreruleset/modsecurity-crs-docker#222]
Hi
Coming along with [#3642](https://github.com/coreruleset/coreruleset/issues/3642) I wonder about the follwing output when starting owasp/modsecurity-crs:nginx container:
```
2024/04/04 16:11:33 [notice] 630#630: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/824/0)
2024/04/04 16:11:37 [notice] 1#1: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/824/0)
2024/04/04 16:11:37 [notice] 1#1: using the "epoll" event method
2024/04/04 16:11:37 [notice] 1#1: nginx/1.25.3
2024/04/04 16:11:37 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
2024/04/04 16:11:37 [notice] 1#1: OS: Linux 6.1.0-18-amd64

```

I am confused for my original issue. For this, may I suggest to add the Modsecurity version (which seems to be 3.0.12 now) to the logging at startup as seen in the first post? Just to be clear about it?

**Comment by ne20002** [comment]
May the problem be line 47 in the Dockerfile?
`git clone https://github.com/SpiderLabs/ModSecurity --branch "v${MODSEC3_VERSION}" --depth 1 --recursive; \
`
where this branch does not exists with version 3.0.12 and therefor the build is not updated?

**Comment by ne20002** [comment]
I am confused for my original issue. For this, may I suggest to add the Modsecurity version (which seems to be 3.0.12 now) to the logging at startup as seen in the first post? Just to be clear about it?

**Comment by theseion** [comment]
Hi @ne20002. I looked through the other issue and wasn't able to find anything that related to logging the version at startup. I'm not aware of an option in ModSecurity to log the ModSecurity version, do you have something in mind on how to do this? The only option I see right now is to print to stdout manually.

**Comment by ne20002** [comment]
As seen in the log output on startup in the post above there are a log statements about nginx version and modesc-nginx? version. Having the modsec version printed would be helpful. From the current output I can't tell if it really is 3.0.12 or something else.
I have no idea on how to do it.

**Comment by airween** [comment]
hi @ne20002,

> Having the modsec version printed would be helpful. From the current output I can't tell if it really is 3.0.12 or something else.

I'm sure this would be a very helpful feature, but I think it's more a ModSecurity-nginx feature than the Docker image.

Would you open a new issue [there](https://github.com/owasp-modsecurity/ModSecurity-nginx/issues). Thanks!

**Comment by theseion** [comment]
@ne20002 got you. I could do that but having ModSecurity do that would be better. Thanks @airween.

**Comment by theseion** [comment]
Created the issue: https://github.com/owasp-modsecurity/ModSecurity-nginx/issues/316.

**Comment by airween** [comment]
Please take a review: https://github.com/owasp-modsecurity/ModSecurity-nginx/pull/319.
