### ISSUE TITLE
MODSEC_AUDIT_STORAGE_DIR variable breaks bootup

### ISSUE THREAD

**Issue by gtaws** [coreruleset/modsecurity-crs-docker#246]
On [4.1.0-nginx-202405050505](https://hub.docker.com/layers/owasp/modsecurity-crs/4.1.0-nginx-202405050505/images/sha256-18e9e624306ad46ef95a55391666eb171fa8fe818775a8634a36ec5627266fd6?context=explore), it seems like a new variable MODSEC_AUDIT_STORAGE_DIR was introduced and added to /etc/modsecurity.d/modsecurity.conf . No documentation for this variable exists. it's breaking boot up of image now with error *[emerg] 1#1: "modsecurity_rules_file" directive Rules error. File: /etc/modsecurity.d/modsecurity.conf. Line: 11. Column: 50. Invalid input:  SecAuditLogStorageDir ${MODSEC_AUDIT_STORAGE_DIR} in /etc/nginx/conf.d/modsecurity.conf:2*. Reverting to [4.1.0-nginx-202404070904](https://hub.docker.com/layers/owasp/modsecurity-crs/4.1.0-nginx-202404070904/images/sha256-268e4e0899d3d22c2046b80c89c35b73825c357a80af3e267fdc0d2dba89f70f?context=explore) fixed the issue for now. Need guidance

**Comment by fzipi** [comment]
Duplicate from #243. There will be a new release today.
