### ISSUE TITLE
Remove env var PROXY and rename UPSTREAM to BACKEND in README.md

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/modsecurity-crs-docker#26]
As a reminder for myself.

**Comment by TRget88** [comment]
Hello franbuehler, So the vars PROXY and UPSTREAM should be replaced by BACKEND? I know this is exactly what you have typed,  I am just trying to figure out why the test I am running is not working. If BACKEND is now used for passing than that should explain my issue.

**Comment by timwsuqld** [comment]
This has caught me out now, the README is incorrect causing the image to not work. It needs to be kept up to date with https://github.com/coreruleset/modsecurity-docker

**Comment by fzipi** [comment]
This was done.
