### ISSUE TITLE
(13)Permission denied: AH00091: httpd: could not open error log file /var/log/apache2/error.log.

### ISSUE THREAD

**Issue by xBounceIT** [coreruleset/modsecurity-crs-docker#267]
Hi,

i tried upgrading my docker container to version 4.3.0-apache from 3.3.5-apache and getting this error.

It is probably due to now being run as an unprivileged user but how can i fix this? I have tried everything but the container refuses to start.

This is the current volume configuration.
    - ./persistence/logs:/var/log/apache2:rw

I aim to log apache access and error logs in /var/log/apache2/access.log and /var/log/apache2/error.log and the various virtualhosts in subfolders of /var/log/apache2 (like /var/log/apache2/vhost1/vhost1_access.log etc.)

Regards,
Daniel D.

**Comment by fzipi** [comment]
Probably [this one](https://github.com/coreruleset/coreruleset/issues/3738) will fix this issue.

**Comment by RedXanadu** [comment]
Hi @xBounceIT

I think this is the same issue I ran into and reported on the CRS repo recently. It is a very annoying breaking change.

Try:

`chmod o+w`

on your logging directory and see if it helps?

**Comment by xBounceIT** [comment]
> Hi @xBounceIT
> 
> I think this is the same issue I ran into and reported on the CRS repo recently. It is a very annoying breaking change.
> 
> Try:
> 
> `chmod o+w`
> 
> on your logging directory and see if it helps?

Yes this does fix the issue but now every user has rights to write in that directory. Might be a dumb question but isn't it the same as having the container running as root since apache alread runs as httpd?

**Comment by RedXanadu** [comment]
I think the containers are root-less now, at least that is my understanding. I believe that it the cause of this problem in the first place.

I'm not a Docker expert, but I think you can use a non-host volume mount type to get around this problem, if chmod o+w is not an acceptable solution.

**Comment by xBounceIT** [comment]
I discovered that you can simply create a docker file and set the user to root

```
FROM owasp/modsecurity-crs:4.3.0-apache-202406090906

USER root
```

I use it to also install mod evasive and upgrade the packages. I will close this issue

**Comment by fzipi** [comment]
The problem is that the user and group id of the files inside the container don't match the ones in the base host, hence you don't have access.

E.g. the user id is probably 1001 or 1002 and yours is different.
