### ISSUE TITLE
Testing code present in the official owasp/modsecurity-crs docker image

### ISSUE THREAD

**Issue by andrzejswiatek** [coreruleset/modsecurity-crs-docker#284]
We use the _owasp/modsecurity-crs:4.2-nginx-202405060805_ image as a base image for our application. We deployed an application on Azure and the EDR (Microsoft Defender for Endpoint) has detected potential malwares in the following path on hosting machine:
_/var/lib/docker/overlay2/…/diff/opt/owasp-crs/tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933111.yaml_.

Currently, the files used to build _modsecurity-csr_ images use the full contents of the [rules repository](https://github.com/coreruleset/coreruleset/) and therefore, the test files are present in one of the layers of the created docker image.

Related [issue](https://github.com/coreruleset/coreruleset/issues/3791) was raised some time ago on the core rule set repository and it seems like there exists [minimalistic pack of ruleset](https://github.com/coreruleset/coreruleset/releases/download/v4.6.0/coreruleset-4.6.0-minimal.tar.gz) produced (without tests files). However this minimalistic version is not used in the Dockerfile for owasp/modsecurity-crs build process. The ideal solution for us would be if official images would use minimal core rule set without tests files.

**Comment by fzipi** [comment]
Ah, makes sense. Let's switch then to minimal.

Thanks for rising this up.

**Comment by andrzejswiatek** [comment]
Thank you very much for your quick response

**Comment by fzipi** [comment]
BTW, the code should be update in the `release/20240913`. It is in the build process, you'll see the release coming out in 4-5 hours.
