### ISSUE TITLE
I can't add modules

### ISSUE THREAD

**Issue by mmoradi-87** [coreruleset/modsecurity-crs-docker#287]
Hello, I want use this image for a website, but I can't add modules like gzip or ngx_http_core_module. And when I set keepalive_requests, container don't start.
How can I enable a module in this image?
How can I set  parameters like keepalive_requests?
Thanks.

**Comment by fzipi** [comment]
You should create your own file and map it to replace the https://github.com/coreruleset/modsecurity-crs-docker/blob/main/nginx/templates/nginx.conf.template file. See the description here: https://github.com/coreruleset/modsecurity-crs-docker?tab=readme-ov-file#nginx-based-images-breaking-change

You can also use environment variables as detailed [in the README.md](https://github.com/coreruleset/modsecurity-crs-docker?tab=readme-ov-file#nginx-env-variables).

**Comment by fzipi** [comment]
Were you able to add modules @mmoradi-87 ?
