### ISSUE TITLE
SecGeoLookupDb not working if we perform a "nginx -s reload"

### ISSUE THREAD

**Issue by Dr-Lazarus-V2** [coreruleset/modsecurity-crs-docker#290]
### Database is not open. Use: SecGeoLookupDb directive." after reload 

**Describe the Bug**
When using `mmdb` to block countries from accessing the website, everything works fine until the `nginx` server is reloaded. After reload, it is not able to work.

It is linked to this issue in modsecurity: [Issue 2041](https://github.com/owasp-modsecurity/ModSecurity/issues/2041)

As a consequence, I would require to restart the container whenever I update the configuration file to block certain countries.

**Comment by Dr-Lazarus-V2** [comment]
The workaround mentioned in this issue, is to only compile the modsecurity engine without "libgeoip-dev" and without the flag:"--with-geoip"

**Comment by Dr-Lazarus-V2** [comment]
Since the legacy GeoIP-dev library does not really server any purpose, would it be okiee to remove it from the image?

**Comment by Dr-Lazarus-V2** [comment]
Apologies for bumping this, is this something the team would be willing to consider? @fzipi

**Comment by fzipi** [comment]
Everything that keeps things working, of course. Sorry for the delay.

**Comment by Dr-Lazarus-V2** [comment]
Alright thank you, I will raise a PR for it!

**Comment by fzipi** [comment]
This should be solved in https://github.com/coreruleset/modsecurity-crs-docker/releases/tag/release%2F20241003.
