### ISSUE TITLE
Make image configurable with more ENV variables

### ISSUE THREAD

**Issue by bittner** [coreruleset/modsecurity-crs-docker#3]
The image currently provides ENV variables for paranoia level and anomaly scores to allow configuring the image behavior at runtime.

We would suggest to add more environment variables to make is easy to use the image out-of-the-box in cloud-native scenarios. The ones we have battle-tested in OpenShift/Kubernetes environments are specified by our [vshn/modsecurity](https://github.com/vshn/modsecurity-docker#configuration) container image.

Any feedback is welcome!

**Comment by bittner** [comment]
We just figured that it makes sense to incorporate the environment variables directly in the [crs-setup.conf](https://github.com/CRS-support/modsecurity-crs-docker/blob/master/3.3-apache/Dockerfile#L24), which [comes from the CRS project](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/crs-setup.conf.example) and is integrated via the `Dockerfile`, currently.

Depending on whether/how we get env variables working with Nginx this may need to have to go into the [entrypoint script](https://github.com/CRS-support/modsecurity-crs-docker/blob/master/src/docker-entrypoint.sh), too.

**Mentioned in:** https://github.com/vshn/modsecurity-docker/pull/43#issuecomment-577180816

**Comment by ZuGao** [comment]
As agreed with @dune73 at Bern meetup we will add the environment variables to the image. The first batch of variables were already added, and there are more to come in a subsequent pull request. We also plan to port the changes to the upstream image as well.

**Comment by bittner** [comment]
Merged #11. More related work happens upstream in https://github.com/CRS-support/modsecurity-docker/pull/38.

**Comment by bittner** [comment]
https://github.com/CRS-support/modsecurity-docker/pull/38 is now ready for code review. A first step towards a plain ModSecurity Docker image generally useful (before loading the CRS). Feel free to give it a shot.

**Comment by bittner** [comment]
PR #38 was merged on March 27. Hence, closing this issue.
