### ISSUE TITLE
Latest version of nginx dockerimage does not run

### ISSUE THREAD

**Issue by ldomesjo** [coreruleset/modsecurity-crs-docker#309]
The latest release seems to have broken the docker image, if you try to run:
`docker run --rm -it owasp/modsecurity-crs:nginx` you end up with the following error:

2024/12/12 07:37:12 [emerg] 1#1: dlopen() "/etc/nginx/modules/ngx_http_headers_more_filter_module.so" failed (/etc/nginx/modules/ngx_http_headers_more_filter_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:3
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_headers_more_filter_module.so" failed (/etc/nginx/modules/ngx_http_headers_more_filter_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:3

I see that line 3 was added with the latest release

**Comment by ldomesjo** [comment]
Just realised you have already fixed this with this PR: https://github.com/coreruleset/modsecurity-crs-docker/pull/307
nicely done!

any chance of getting a new release? :)

**Comment by theseion** [comment]
Sure. I'll trigger a new release now. It will take a while for the builds to complete though.
