### ISSUE TITLE
The REPORTING_LEVEL environment variable

### ISSUE THREAD

**Issue by spatterIight** [coreruleset/modsecurity-crs-docker#311]
The README is missing information as to what the `REPORTING_LEVEL` environment variable does. I could not find anything on the [official docs](https://coreruleset.org/docs/) either.

**Comment by theseion** [comment]
Thanks @spatterIight. We'll fix that. Reporting level refers to rule `900115`: https://github.com/coreruleset/coreruleset/blob/1a8f408ea730c7447e0dbb009ac3cef88368f74e/crs-setup.conf.example#L349

**Comment by spatterIight** [comment]
thanks, love this project and the work you all do 🫡
