### ISSUE TITLE
Upstream supports more ENV vars

### ISSUE THREAD

**Issue by timwsuqld** [coreruleset/modsecurity-crs-docker#32]
`src/etc/modsecurity.d/modsecurity-override.conf` in upstream is more configurable than in this image.

https://github.com/coreruleset/modsecurity-crs-docker/blob/master/src/etc/modsecurity.d/modsecurity-override.conf
vs
https://github.com/coreruleset/modsecurity-docker/blob/master/src/etc/modsecurity.d/modsecurity-override.conf

Upstream allows things like `MODSEC_AUDIT_LOG_TYPE` to override the image.

**Comment by franbuehler** [comment]
Hi @timwsuqld!

Thank you for your report.
We'll investigate this issues.

**Comment by franbuehler** [comment]
I'll provide a PR that will consolidate both files.

Or if you want to provide a PR, please just go ahead @timwsuqld?

**Comment by timwsuqld** [comment]
After more investigation, I don't see why we can't just stop override the `modsecurity-override.conf` file from upstream. I can't see anything that we add to it for our use? I think it was in this repo before it was updated upstream, but now we could just remove it from our build.

**Comment by franbuehler** [comment]
Oh yeah, that's smart. @fzipi , do you see something that speaks against it?

**Comment by fzipi** [comment]
100% agreed. Let's go for it!

**Comment by franbuehler** [comment]
Do you want to provide a PR @timwsuqld or shall I?

**Comment by timwsuqld** [comment]
@franbuehler PR created

**Comment by franbuehler** [comment]
Great, thank you very much for the PR!
I will test the behavior and review the PR.
