### ISSUE TITLE
"Minor versions" tags of docker images are not updated anymore

### ISSUE THREAD

**Issue by TheBigLee** [coreruleset/modsecurity-crs-docker#38]
Since the refactoring of the github actions, the minor version tags of the docker images are not updated anymore.

Eg. the tag `3.3-apache` has not been updated when the new `3.3.2`version has been released.

The github actions should be adjusted, so that a patch-level release will also update the minor tag version of that image.

**Comment by fzipi** [comment]
Thanks for the report, will take a look.

**Comment by fzipi** [comment]
Wait: 3.3 you said? That's the old naming scheme. Take a look at the README.md to see the new one.
