### ISSUE TITLE
Websockets: 400 Bad Request

### ISSUE THREAD

**Issue by jamesmeneghello** [coreruleset/modsecurity-crs-docker#42]
Websocket requests seem to be broken. Looks like an error in the Nginx config (`/etc/nginx/conf.d/default.conf`):

```
        proxy_set_header Upgrade $connection_upgrade;
        proxy_set_header Connection $connection_upgrade;
```

Should instead be:

```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
```

**Comment by fzipi** [comment]
Basically that setting comes from the map above:
```
 map $http_upgrade $connection_upgrade {
     default upgrade;
     '' close;
 }
```
@jamesmeneghello Do we need to fix the map instead?

**Comment by fzipi** [comment]
@jamesmeneghello Any comments? Otherwise, we are closing this one.

**Comment by fzipi** [comment]
Thanks for the explanation, reopening.
