### ISSUE TITLE
Error uploading files using v3.3.2 - Multipart parsing error: Multipart: Final boundary missing.

### ISSUE THREAD

**Issue by archletekke** [coreruleset/modsecurity-crs-docker#48]
With the last update (and removal of old images - why, btw?) to 3.3.2 we can not upload files anymore properly without triggering the following error:

```
[error] 24#24: *338 [client 10.70.0.7] ModSecurity: Access denied with code 400 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/etc/modsecurity.d/modsecurity.conf"] [line "60"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Multipart parsing error: Multipart: Final boundary missing."] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "10.244.2.12"]
```

Is this some kind of a regression or did something change with the rules that would cause this behaviour change?

Using the 3.3.2-nginx image.

**Comment by Darkguver** [comment]
Hi we experienced the same issues,
and regarding the audit logging it has to do with the :
```
SecDataDir ${MODSEC_DATA_DIR}
SecTmpDir ${MODSEC_TMP_DIR}
SecUploadDir ${MODSEC_UPLOAD_DIR}
```

The Owasp is trying to write this to non existing folders by default it works for us by overwriting these env vars to /tmp

**Comment by eshaan7** [comment]
+1.

**Comment by archletekke** [comment]
> Hi we experienced the same issues, and regarding the audit logging it has to do with the :
> 
> ```
> SecDataDir ${MODSEC_DATA_DIR}
> SecTmpDir ${MODSEC_TMP_DIR}
> SecUploadDir ${MODSEC_UPLOAD_DIR}
> ```
> 
> The Owasp is trying to write this to non existing folders by default it works for us by overwriting these env vars to /tmp

Did you just override them in the custom config section in the nginx.conf file? Or rather in the env variables of the dockerfile?

**Comment by archletekke** [comment]
Changing the values in the Dockerfile worked for me. Ideally, this should still be fixed in the repo itself tho.

**Comment by fzipi** [comment]
Closing.
