### ISSUE TITLE
ModSecurity not compiled with GeoIP support on arm64

### ISSUE THREAD

**Issue by rfricz** [coreruleset/modsecurity-crs-docker#51]
Hi, when running the nginx image on arm64 arch, I have to disable (delete) the REQUEST-910-IP-REPUTATION rule to be able to start nginx, otherwise it fails with
```
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/modsecurity.d/owasp-crs/rules/REQUEST-910-IP-REPUTATION.conf. Line: 76. Column: 22. This version of ModSecurity was not compiled with GeoIP or MaxMind support.  in /etc/nginx/conf.d/modsecurity.conf:2
```
The amd64 arch doesn't have this problem.

I can see that libgeoip-dev is installed in the owasp/modsecurity:nginx image before building ModSecurity, so I don't understand why it fails. I have tried installing various packages (libgeoip1 libgeoip-dev geoip-database geoip-database-extra geoip-bin) into the container, but it doesn't help. Am I missing something? Could you please verify that ModSecurity gets built with GeoIP or MaxMind support?

Thanks so much for providing this image.

**Comment by fzipi** [comment]
This is solved by https://github.com/coreruleset/modsecurity-docker/pull/98.

**Comment by fzipi** [comment]
@rfricz It is building now, should take ~~ 4 hours.
