### ISSUE TITLE
Default USER=daemon conflicts with modsecurity-docker

### ISSUE THREAD

**Issue by woefe** [coreruleset/modsecurity-crs-docker#54]
The parent modsecurity-docker image uses `www-data` by default and [`chown`s temporary files to that user](https://github.com/coreruleset/modsecurity-docker/blob/c6ec7ffe17c0b14309779f7ad21bc3498a663e94/v2-apache/Dockerfile#L128). The modsecurity-crs-docker image uses the `daemon` user by default (see [Dockerfile](https://github.com/coreruleset/modsecurity-crs-docker/blob/66d1883852e3ff1c2b4fa937579d315fb33d659b/apache/Dockerfile#L13) and [httpd-modsecurity.conf](https://github.com/coreruleset/modsecurity-crs-docker/blob/66d1883852e3ff1c2b4fa937579d315fb33d659b/apache/conf/extra/httpd-modsecurity.conf#L7)), which causes following errors for me
```
ModSecurity: collections_remove_stale: Failed to access DBM file "/tmp/modsecurity/data/daemon-ip": Permission denied
```

As a workaround I can set `USER=www-data` in the environment of the container and the errors disappear.

I have two questions on this:
1. Is there any particular reason this image does not use the default www-data user?
2. Why is the `USER` set in modsecurity-crs-docker and not in the parent modsecurity-docker and would it make sense to move that logic to the parent image?

**Comment by fzipi** [comment]
Hey, thanks for creating this one.

There was a bug in upstream httpd image that was recently fixed.

Let me take a look and see if we can fix this for good.

**Comment by fzipi** [comment]
This is definitely a bug, should be changed to www-data. Will send a PR.
