### ISSUE TITLE
Support for analyzing gzip-ed body requests

### ISSUE THREAD

**Issue by pestebogdan** [coreruleset/modsecurity-crs-docker#60]
Trying to send a gzip-ed body cannot be parsed:

```
curl ....
--header 'Content-Encoding: gzip' \
--header 'Content-Type: application/json' \
--data-binary '@body.json.gz'
```

Error:

```
file: "/etc/modsecurity.d/modsecurity.conf"
lineNumber: "65"
match: "Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' )"
maturity: "0"
reference: "v192,1"
rev: ""
ruleId: "200002"
severity: "2"

message: "Failed to parse request body."

```

The only solution I see is setting `MODSEC_REQ_BODY_ACCESS=off` but that opens up a lot of security holes.

Is there any support for handling such requests ?

**Comment by fzipi** [comment]
HI @pestebogdan ! Do you think this is a problem with this docker setup, or it is more a problem for ModSecurity and the nginx connector?

**Comment by fzipi** [comment]
@pestebogdan I think this is a native problem and doesn't depend on this docker setup. This should be solved ad the ModSecurity-nginx level I think. Can you cross post this problem there? I don't think here we can solve it.

Closing.

**Comment by bogdan-ionut-peste-db** [comment]
Ok, that's fair enough. Just thought there might be some input that alleviates this that i may have missed. Will follow through upstream with this issue. Thanks.
