### ISSUE TITLE
docker-entrypoint copy in wrong order?

### ISSUE THREAD

**Issue by ne20002** [coreruleset/modsecurity-crs-docker#84]
Hi
Looking on the log of my started container I wonder if there might be a problem with the order of the processed scripts. 
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/conf.d/modsecurity.conf.template to /etc/nginx/conf.d/modsecurity.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/conf.d/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/conf.d/logging.conf.template to /etc/nginx/conf.d/logging.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/modsecurity.d/setup.conf.template to /etc/nginx/modsecurity.d/setup.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template to /etc/nginx/modsecurity.d/modsecurity-override.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/includes/location_common.conf.template to /etc/nginx/includes/location_common.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/includes/proxy_backend.conf.template to /etc/nginx/includes/proxy_backend.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/nginx.conf.template to /etc/nginx/nginx.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/90-copy-modsecurity-config.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/91-update-resolver.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/92-update-real_ip.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/95-activate-rules.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/96-configure-plugin-includes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```
I believe the script _20-envsubst-on-templates.sh_ overwrites the file _/etc/nginx/conf.d/default.conf_ which has been modified before in _10-listen-on-ipv6-by-default.sh_.

**Comment by theseion** [comment]
Thanks for the report @ne20002.

You're right, we override that file after IPv6 has been enabled. I don't think that's a problem though. If you want to enable IPv6 you can simply override that file. You could also provide a PR to make it configurable if you think others would benefit from that too.

Do you need IPv6?

**Comment by ne20002** [comment]
My systems are dual stack enabled but as far as I see, the Nginx proxy forwards IPv6 connections via IPv4 to the upstream servers (e.g. this one). I'm not sure if this is a performance issue but it works. 

I also wonder about this whole process about copying template files. As the Nginx base image allows to be runned in read-only mode aka read-only root file system, this template copying breaks this option.
I need to have a look into the template files and try to understand what the documentation says about this. A far as I understand, I can mount/override the template directory and include only the files I want to be overwritten. The files also already exist in the conf directory allready with default values?
At the moment I use my own nginx.conf.template and modesecurity/main.conf without any further substitutions so maybe I can skip the whole overriding stuff.

**Comment by theseion** [comment]
>The files also already exist in the conf directory allready with default values?

The conf files don't have default values, just placeholders. The default values are set in the Dockerfile at build time.

> At the moment I use my own nginx.conf.template and modesecurity/main.conf without any further substitutions so maybe I can skip the whole overriding stuff.

Absolutely. We can't cover every variable or use case, so it's perfectly normal to just supply your own and ignore all of the variables.

I'll close this issue. We can reopen it if the need arises.
