### ISSUE TITLE
Please don't reuse version tags on Docker Hub! Image was unexpectedly overwritten.

### ISSUE THREAD

**Issue by andrei-piarainc** [coreruleset/modsecurity-crs-docker#87]
We used tag "owasp/modsecurity-crs:3.3.2-nginx" in our setup and once after restart of the environment (with cleaning docker images cache) we suddenly realized that our application does not work anymore. The reason was changed modsecurity nginx image, that was uploaded on Docker Hub under the same tag! This was completely unexpected. Normally one can expect that image being published once under some version tag on Docker Hub will be never overwritten. **New updated images should be published under the different version tag. Otherwise it cannot be used in production!**
We were lucky that this happened in non-production environment and now we are forced to upload proper images manually to our environments to keep it under control, which is very problematic.
I understand the idea to keep version of underlying software in the image tag, this is very useful of course, but then additional segment of image version should be added to tag, e.g. "modsecurity-crs:3.3.2-nginx-img-1.1"

**Comment by fzipi** [comment]
Thanks for reporting. We are aware of this, there is an open issue, #67.

**Comment by fzipi** [comment]
@andrei-piarainc The changes are live now. Can you test them and see if they work for your use case?

**Comment by andrei-piarainc** [comment]
> 

Thanks! I had some problems with certificates on recent builds of nginx-based image, that is why I noticed the problem with tags, but I'll test getting new tags at least.

**Comment by andrei-piarainc** [comment]
> @andrei-piarainc The changes are live now. Can you test them and see if they work for your use case?

I've tested build of our image based on new tag `owasp/modsecurity-crs:3.3.4-nginx-202209221209`
Build was successful, and container started OK.
It still does not work because of problem with certificates, but I'll report it in a separate issue.
