### ISSUE TITLE
How to pass error messages from backend.

### ISSUE THREAD

**Issue by TafkaMax** [coreruleset/modsecurity-crs-docker#94]
Hi

We are having a small issue, where all of the error messages come from the proxy and are not passed from the backend application.

# Inside the docker container

## List of files that are involved.

```
root@apache-modsecurity-proxy:/usr/local/apache2/conf/extra/httpd-multilang-errordoc.conf
root@apache-modsecurity-proxy:/usr/local/apache2/error/*
root@apache-modsecurity-proxy:/usr/local/apache2/conf/httpd.conf
```

Now the problem is that inside the container the apache configuration httpd.conf does NOT include the httpd-multilang-errordoc.conf by default. It is commented out.

I can't seem to find any other place where the custom error messages are loaded in.

**Comment by fzipi** [comment]
Hi!

which error are you trying to show?

**Comment by TafkaMax** [comment]
I will expand on this a little. 

We have a keycloak installation and an application that use it for authentication.

Keycloak uses the modsecurity-crs:apache and the application uses the modsecurity-crs:nginx 

Keycloak should return an 401 unauthorized to the user, but it returns this.

![image](https://user-images.githubusercontent.com/46354923/196784821-d4a9826e-6b08-4d53-a16c-47dd939d2e55.png)

**Comment by fzipi** [comment]
The problem is that apache is doing `ProxyErrorOverride on`.

**Comment by fzipi** [comment]
Quick option for testing this: get [this file](https://github.com/coreruleset/modsecurity-docker/blob/develop/v2-apache/conf/extra/httpd-vhosts.conf), save it locally. Change ProxyErrorOverride to off. Use docker-compose or other to volume mount your local file over the original. Test and see if that solves your problem.

**Comment by TafkaMax** [comment]
Yes, that worked, thank you for the help!

**Comment by fzipi** [comment]
We can add that as an env variable.
