### ISSUE TITLE
Sign images using cosign

### ISSUE THREAD

**Issue by fzipi** [coreruleset/modsecurity-crs-docker#96]
Check what is needed to sign images using cosign.

References
- https://github.com/sigstore/cosign-installer

**Comment by fzipi** [comment]
See https://slsa.dev/blog/2023/02/slsa-github-workflows-container-ga.

**Comment by fzipi** [comment]
Looks like this worked!
<img width="907" alt="image" src="https://github.com/coreruleset/modsecurity-crs-docker/assets/3012076/d6953e01-7af8-439f-b69f-3000864e85a8">

**Comment by theseion** [comment]
Awesome!
